
◊root"_tf_keras_model*∑{"name": "co_vi_t_model", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "CoViTModel", "config": {"N": 2, "d_out": 50, "d_key": 64, "d_val": 64, "d_model": 256, "heads": 8, "dropout_rate": 0.1, "d_ff": 1024}, "shared_object_id": 0, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 192, 256, 4]}, "float32", "input_1"]}], {}]}, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 192, 256, 4]}, "float32", "input_1"]}, "keras_version": "2.9.0", "backend": "tensorflow", "model_config": {"class_name": "CoViTModel", "config": {"N": 2, "d_out": 50, "d_key": 64, "d_val": 64, "d_model": 256, "heads": 8, "dropout_rate": 0.1, "d_ff": 1024}}, "training_config": {"loss": "categorical_crossentropy", "metrics": [[{"class_name": "TopKCategoricalAccuracy", "config": {"name": "top1_accuracy", "dtype": "float32", "k": 1}, "shared_object_id": 1}, {"class_name": "TopKCategoricalAccuracy", "config": {"name": "top2_accuracy", "dtype": "float32", "k": 2}, "shared_object_id": 2}, {"class_name": "TopKCategoricalAccuracy", "config": {"name": "top5_accuracy", "dtype": "float32", "k": 5}, "shared_object_id": 3}]], "weighted_metrics": null, "loss_weights": null, "optimizer_config": {"class_name": "Adam", "config": {"name": "Adam", "clipnorm": 1.0, "learning_rate": 0.0010000000474974513, "decay": 0.0, "beta_1": 0.8999999761581421, "beta_2": 0.9990000128746033, "epsilon": 1e-07, "amsgrad": false}}}}2
¨root.base_embedding"_tf_keras_layer*˚{"name": "linear", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear", "trainable": true, "dtype": "float32", "units": 1}, "shared_object_id": 4, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256, 4]}}2
á
	root.norm"_tf_keras_layer*‡{"name": "layer_normalization_4", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_4", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 5}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 6}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 7, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
¥root.out"_tf_keras_layer*é{"name": "predictor_block", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "PredictorBlock", "config": {"name": "predictor_block", "trainable": true, "dtype": "float32", "units": 50}, "shared_object_id": 8, "build_input_shape": {"class_name": "TensorShape", "items": [null, 256]}}2
æüroot.encoder_blocks.0"_tf_keras_layer*ä{"name": "encoder_block", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderBlock", "config": {"name": "encoder_block", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 8, "dropout_rate": 0.1, "d_ff": 1024}, "shared_object_id": 9}2
√†root.encoder_blocks.1"_tf_keras_layer*è{"name": "encoder_block_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderBlock", "config": {"name": "encoder_block_1", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 8, "dropout_rate": 0.1, "d_ff": 1024}, "shared_object_id": 10}2
∫∏root.keras_api.metrics.0"_tf_keras_metric*Ç{"class_name": "Mean", "name": "loss", "dtype": "float32", "config": {"name": "loss", "dtype": "float32"}, "shared_object_id": 11}2
Êπroot.keras_api.metrics.1"_tf_keras_metric*Æ{"class_name": "TopKCategoricalAccuracy", "name": "top1_accuracy", "dtype": "float32", "config": {"name": "top1_accuracy", "dtype": "float32", "k": 1}, "shared_object_id": 1}2
Ê∫root.keras_api.metrics.2"_tf_keras_metric*Æ{"class_name": "TopKCategoricalAccuracy", "name": "top2_accuracy", "dtype": "float32", "config": {"name": "top2_accuracy", "dtype": "float32", "k": 2}, "shared_object_id": 2}2
Êªroot.keras_api.metrics.3"_tf_keras_metric*Æ{"class_name": "TopKCategoricalAccuracy", "name": "top5_accuracy", "dtype": "float32", "config": {"name": "top5_accuracy", "dtype": "float32", "k": 5}, "shared_object_id": 3}2
—…root.encoder_blocks.0.mha"_tf_keras_layer*ô{"name": "my_multi_head_attention", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "MyMultiHeadAttention", "config": {"name": "my_multi_head_attention", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 8, "dropout_rate": 0.1}, "shared_object_id": 12}2
É root.encoder_blocks.0.ff"_tf_keras_layer*Ã{"name": "feed_forward", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "FeedForward", "config": {"name": "feed_forward", "trainable": true, "dtype": "float32", "units": 1024, "activation": "relu", "outer_units": 256, "dropout_rate": 0.1}, "shared_object_id": 13, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ôÀroot.encoder_blocks.0.norm1"_tf_keras_layer*ﬂ{"name": "layer_normalization", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 14}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 15}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 16, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ùÃroot.encoder_blocks.0.norm2"_tf_keras_layer*„{"name": "layer_normalization_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 17}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 18}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 19, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
’‘root.encoder_blocks.1.mha"_tf_keras_layer*ù{"name": "my_multi_head_attention_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "MyMultiHeadAttention", "config": {"name": "my_multi_head_attention_1", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 8, "dropout_rate": 0.1}, "shared_object_id": 20}2
á’root.encoder_blocks.1.ff"_tf_keras_layer*–{"name": "feed_forward_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "FeedForward", "config": {"name": "feed_forward_1", "trainable": true, "dtype": "float32", "units": 1024, "activation": "relu", "outer_units": 256, "dropout_rate": 0.1}, "shared_object_id": 21, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ù÷root.encoder_blocks.1.norm1"_tf_keras_layer*„{"name": "layer_normalization_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 22}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 23}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 24, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ù◊root.encoder_blocks.1.norm2"_tf_keras_layer*„{"name": "layer_normalization_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_3", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 25}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 26}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 27, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Øç3root.encoder_blocks.0.mha.scaled_dot_prod_attention"_tf_keras_layer*›{"name": "scaled_dot_product_attention", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ScaledDotProductAttention", "config": {"name": "scaled_dot_product_attention", "trainable": true, "dtype": "float32"}, "shared_object_id": 28}2
¡é!root.encoder_blocks.0.mha.lin_out"_tf_keras_layer*Å{"name": "linear_25", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_25", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 29, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 512]}}2
ﬂè!root.encoder_blocks.0.mha.dropout"_tf_keras_layer*ü{"name": "dropout", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 30, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
≈ó$root.encoder_blocks.0.ff.outer_layer"_tf_keras_layer*Ç{"name": "linear_26", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_26", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 31, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 1024]}}2
‚ò root.encoder_blocks.0.ff.dropout"_tf_keras_layer*£{"name": "dropout_1", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_1", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 32, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
≥Ω3root.encoder_blocks.1.mha.scaled_dot_prod_attention"_tf_keras_layer*·{"name": "scaled_dot_product_attention_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ScaledDotProductAttention", "config": {"name": "scaled_dot_product_attention_1", "trainable": true, "dtype": "float32"}, "shared_object_id": 33}2
¡æ!root.encoder_blocks.1.mha.lin_out"_tf_keras_layer*Å{"name": "linear_51", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_51", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 34, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 512]}}2
„ø!root.encoder_blocks.1.mha.dropout"_tf_keras_layer*£{"name": "dropout_2", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_2", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 35, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
≈«$root.encoder_blocks.1.ff.outer_layer"_tf_keras_layer*Ç{"name": "linear_52", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_52", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 36, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 1024]}}2
‚» root.encoder_blocks.1.ff.dropout"_tf_keras_layer*£{"name": "dropout_3", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_3", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 37, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆˘)root.encoder_blocks.0.mha.lin_key_heads.0"_tf_keras_layer*˛{"name": "linear_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_1", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 38, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆˙)root.encoder_blocks.0.mha.lin_key_heads.1"_tf_keras_layer*˛{"name": "linear_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_2", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 39, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆˚)root.encoder_blocks.0.mha.lin_key_heads.2"_tf_keras_layer*˛{"name": "linear_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_3", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 40, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆¸)root.encoder_blocks.0.mha.lin_key_heads.3"_tf_keras_layer*˛{"name": "linear_4", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_4", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 41, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆˝)root.encoder_blocks.0.mha.lin_key_heads.4"_tf_keras_layer*˛{"name": "linear_5", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_5", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 42, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆˛)root.encoder_blocks.0.mha.lin_key_heads.5"_tf_keras_layer*˛{"name": "linear_6", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_6", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 43, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆ˇ)root.encoder_blocks.0.mha.lin_key_heads.6"_tf_keras_layer*˛{"name": "linear_7", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_7", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 44, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆Ä)root.encoder_blocks.0.mha.lin_key_heads.7"_tf_keras_layer*˛{"name": "linear_8", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_8", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 45, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆Å)root.encoder_blocks.0.mha.lin_qry_heads.0"_tf_keras_layer*˛{"name": "linear_9", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_9", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 46, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ç)root.encoder_blocks.0.mha.lin_qry_heads.1"_tf_keras_layer*Ä{"name": "linear_10", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_10", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 47, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»É)root.encoder_blocks.0.mha.lin_qry_heads.2"_tf_keras_layer*Ä{"name": "linear_11", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_11", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 48, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ñ)root.encoder_blocks.0.mha.lin_qry_heads.3"_tf_keras_layer*Ä{"name": "linear_12", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_12", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 49, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ö)root.encoder_blocks.0.mha.lin_qry_heads.4"_tf_keras_layer*Ä{"name": "linear_13", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_13", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 50, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ü)root.encoder_blocks.0.mha.lin_qry_heads.5"_tf_keras_layer*Ä{"name": "linear_14", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_14", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 51, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»á)root.encoder_blocks.0.mha.lin_qry_heads.6"_tf_keras_layer*Ä{"name": "linear_15", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_15", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 52, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»à)root.encoder_blocks.0.mha.lin_qry_heads.7"_tf_keras_layer*Ä{"name": "linear_16", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_16", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 53, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»â)root.encoder_blocks.0.mha.lin_val_heads.0"_tf_keras_layer*Ä{"name": "linear_17", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_17", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 54, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»ä)root.encoder_blocks.0.mha.lin_val_heads.1"_tf_keras_layer*Ä{"name": "linear_18", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_18", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 55, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»ã)root.encoder_blocks.0.mha.lin_val_heads.2"_tf_keras_layer*Ä{"name": "linear_19", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_19", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 56, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»å)root.encoder_blocks.0.mha.lin_val_heads.3"_tf_keras_layer*Ä{"name": "linear_20", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_20", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 57, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»ç)root.encoder_blocks.0.mha.lin_val_heads.4"_tf_keras_layer*Ä{"name": "linear_21", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_21", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 58, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»é)root.encoder_blocks.0.mha.lin_val_heads.5"_tf_keras_layer*Ä{"name": "linear_22", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_22", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 59, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»è)root.encoder_blocks.0.mha.lin_val_heads.6"_tf_keras_layer*Ä{"name": "linear_23", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_23", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 60, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»ê)root.encoder_blocks.0.mha.lin_val_heads.7"_tf_keras_layer*Ä{"name": "linear_24", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_24", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 61, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
áó;root.encoder_blocks.0.mha.scaled_dot_prod_attention.softmax"_tf_keras_layer*≠{"name": "softmax", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Softmax", "config": {"name": "softmax", "trainable": true, "dtype": "float32", "axis": -1}, "shared_object_id": 62}2
»Ê)root.encoder_blocks.1.mha.lin_key_heads.0"_tf_keras_layer*Ä{"name": "linear_27", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_27", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 63, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Á)root.encoder_blocks.1.mha.lin_key_heads.1"_tf_keras_layer*Ä{"name": "linear_28", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_28", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 64, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ë)root.encoder_blocks.1.mha.lin_key_heads.2"_tf_keras_layer*Ä{"name": "linear_29", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_29", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 65, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»È)root.encoder_blocks.1.mha.lin_key_heads.3"_tf_keras_layer*Ä{"name": "linear_30", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_30", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 66, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Í)root.encoder_blocks.1.mha.lin_key_heads.4"_tf_keras_layer*Ä{"name": "linear_31", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_31", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 67, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Î)root.encoder_blocks.1.mha.lin_key_heads.5"_tf_keras_layer*Ä{"name": "linear_32", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_32", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 68, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ï)root.encoder_blocks.1.mha.lin_key_heads.6"_tf_keras_layer*Ä{"name": "linear_33", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_33", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 69, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ì)root.encoder_blocks.1.mha.lin_key_heads.7"_tf_keras_layer*Ä{"name": "linear_34", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_34", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 70, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ó)root.encoder_blocks.1.mha.lin_qry_heads.0"_tf_keras_layer*Ä{"name": "linear_35", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_35", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 71, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ô)root.encoder_blocks.1.mha.lin_qry_heads.1"_tf_keras_layer*Ä{"name": "linear_36", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_36", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 72, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»)root.encoder_blocks.1.mha.lin_qry_heads.2"_tf_keras_layer*Ä{"name": "linear_37", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_37", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 73, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ò)root.encoder_blocks.1.mha.lin_qry_heads.3"_tf_keras_layer*Ä{"name": "linear_38", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_38", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 74, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ú)root.encoder_blocks.1.mha.lin_qry_heads.4"_tf_keras_layer*Ä{"name": "linear_39", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_39", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 75, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Û)root.encoder_blocks.1.mha.lin_qry_heads.5"_tf_keras_layer*Ä{"name": "linear_40", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_40", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 76, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ù)root.encoder_blocks.1.mha.lin_qry_heads.6"_tf_keras_layer*Ä{"name": "linear_41", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_41", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 77, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»ı)root.encoder_blocks.1.mha.lin_qry_heads.7"_tf_keras_layer*Ä{"name": "linear_42", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_42", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 78, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»ˆ)root.encoder_blocks.1.mha.lin_val_heads.0"_tf_keras_layer*Ä{"name": "linear_43", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_43", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 79, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»˜)root.encoder_blocks.1.mha.lin_val_heads.1"_tf_keras_layer*Ä{"name": "linear_44", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_44", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 80, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»¯)root.encoder_blocks.1.mha.lin_val_heads.2"_tf_keras_layer*Ä{"name": "linear_45", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_45", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 81, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»˘)root.encoder_blocks.1.mha.lin_val_heads.3"_tf_keras_layer*Ä{"name": "linear_46", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_46", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 82, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»˙)root.encoder_blocks.1.mha.lin_val_heads.4"_tf_keras_layer*Ä{"name": "linear_47", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_47", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 83, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»˚)root.encoder_blocks.1.mha.lin_val_heads.5"_tf_keras_layer*Ä{"name": "linear_48", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_48", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 84, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»¸)root.encoder_blocks.1.mha.lin_val_heads.6"_tf_keras_layer*Ä{"name": "linear_49", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_49", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 85, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»˝)root.encoder_blocks.1.mha.lin_val_heads.7"_tf_keras_layer*Ä{"name": "linear_50", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_50", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 86, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ãÑ;root.encoder_blocks.1.mha.scaled_dot_prod_attention.softmax"_tf_keras_layer*±{"name": "softmax_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Softmax", "config": {"name": "softmax_1", "trainable": true, "dtype": "float32", "axis": -1}, "shared_object_id": 87}2