
Ù	root"_tf_keras_model*‘	{"name": "co_vi_t_model", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "CoViTModel", "config": {"layer was saved without config": true}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 196, 256, 4]}, "float32", "input_1"]}], {}]}, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 196, 256, 4]}, "float32", "input_1"]}, "keras_version": "2.8.0", "backend": "tensorflow", "model_config": {"class_name": "CoViTModel"}, "training_config": {"loss": "categorical_crossentropy", "metrics": [[{"class_name": "MeanMetricWrapper", "config": {"name": "accuracy", "dtype": "float32", "fn": "categorical_accuracy"}, "shared_object_id": 0}]], "weighted_metrics": null, "loss_weights": null, "optimizer_config": {"class_name": "Adam", "config": {"name": "Adam", "learning_rate": 0.0010000000474974513, "decay": 0.0, "beta_1": 0.8999999761581421, "beta_2": 0.9990000128746033, "epsilon": 1e-07, "amsgrad": false}}}}2
¨root.base_embedding"_tf_keras_layer*˚{"name": "linear", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear", "trainable": true, "dtype": "float32", "units": 1}, "shared_object_id": 1, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256, 4]}}2
ˇ	root.norm"_tf_keras_layer*ÿ{"name": "normalization_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": true, "class_name": "Normalization", "config": {"name": "normalization_1", "trainable": true, "dtype": "float32", "axis": {"class_name": "__tuple__", "items": [-1]}, "mean": null, "variance": null}, "shared_object_id": 2, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
≥root.out"_tf_keras_layer*ç{"name": "predictor_block", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "PredictorBlock", "config": {"name": "predictor_block", "trainable": true, "dtype": "float32", "units": 5}, "shared_object_id": 3, "build_input_shape": {"class_name": "TensorShape", "items": [null, 256]}}2
Ÿroot.encoder_blocks.0"_tf_keras_layer*¶{"name": "encoder_block", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderBlock", "config": {"name": "encoder_block", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 8, "dropout_rate": 0.1, "activation": "relu", "outer_units": 256}, "shared_object_id": 4}2
œproot.encoder_blocks.0.mha"_tf_keras_layer*ò{"name": "my_multi_head_attention", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "MyMultiHeadAttention", "config": {"name": "my_multi_head_attention", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 8, "dropout_rate": 0.1}, "shared_object_id": 5}2
Úqroot.encoder_blocks.0.ff"_tf_keras_layer*º{"name": "feed_forward", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "FeedForward", "config": {"name": "feed_forward", "trainable": true, "dtype": "float32", "activation": "relu", "outer_units": 256, "dropout_rate": 0.1}, "shared_object_id": 6, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
årroot.encoder_blocks.0.norm"_tf_keras_layer*‘{"name": "normalization", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": true, "class_name": "Normalization", "config": {"name": "normalization", "trainable": true, "dtype": "float32", "axis": {"class_name": "__tuple__", "items": [-1]}, "mean": null, "variance": null}, "shared_object_id": 7, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
∏~root.keras_api.metrics.0"_tf_keras_metric*Å{"class_name": "Mean", "name": "loss", "dtype": "float32", "config": {"name": "loss", "dtype": "float32"}, "shared_object_id": 8}2
Îroot.keras_api.metrics.1"_tf_keras_metric*¥{"class_name": "MeanMetricWrapper", "name": "accuracy", "dtype": "float32", "config": {"name": "accuracy", "dtype": "float32", "fn": "categorical_accuracy"}, "shared_object_id": 0}2
ÆÉ3root.encoder_blocks.0.mha.scaled_dot_prod_attention"_tf_keras_layer*‹{"name": "scaled_dot_product_attention", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ScaledDotProductAttention", "config": {"name": "scaled_dot_product_attention", "trainable": true, "dtype": "float32"}, "shared_object_id": 9}2
¡Ñ!root.encoder_blocks.0.mha.lin_out"_tf_keras_layer*Å{"name": "linear_25", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_25", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 10, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 512]}}2
ﬂÖ!root.encoder_blocks.0.mha.dropout"_tf_keras_layer*ü{"name": "dropout", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 11, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
≈å$root.encoder_blocks.0.ff.outer_layer"_tf_keras_layer*Ç{"name": "linear_26", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_26", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 12, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 2048]}}2
‚ç root.encoder_blocks.0.ff.dropout"_tf_keras_layer*£{"name": "dropout_1", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_1", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 13, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
∆ß)root.encoder_blocks.0.mha.lin_key_heads.0"_tf_keras_layer*˛{"name": "linear_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_1", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 14, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
∆®)root.encoder_blocks.0.mha.lin_key_heads.1"_tf_keras_layer*˛{"name": "linear_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_2", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 15, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
∆©)root.encoder_blocks.0.mha.lin_key_heads.2"_tf_keras_layer*˛{"name": "linear_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_3", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 16, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
∆™)root.encoder_blocks.0.mha.lin_key_heads.3"_tf_keras_layer*˛{"name": "linear_4", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_4", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 17, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
∆´)root.encoder_blocks.0.mha.lin_key_heads.4"_tf_keras_layer*˛{"name": "linear_5", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_5", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 18, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
∆¨)root.encoder_blocks.0.mha.lin_key_heads.5"_tf_keras_layer*˛{"name": "linear_6", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_6", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 19, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
∆≠)root.encoder_blocks.0.mha.lin_key_heads.6"_tf_keras_layer*˛{"name": "linear_7", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_7", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 20, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
∆Æ)root.encoder_blocks.0.mha.lin_key_heads.7"_tf_keras_layer*˛{"name": "linear_8", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_8", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 21, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
∆Ø)root.encoder_blocks.0.mha.lin_qry_heads.0"_tf_keras_layer*˛{"name": "linear_9", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_9", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 22, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»∞)root.encoder_blocks.0.mha.lin_qry_heads.1"_tf_keras_layer*Ä{"name": "linear_10", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_10", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 23, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»±)root.encoder_blocks.0.mha.lin_qry_heads.2"_tf_keras_layer*Ä{"name": "linear_11", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_11", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 24, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»≤)root.encoder_blocks.0.mha.lin_qry_heads.3"_tf_keras_layer*Ä{"name": "linear_12", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_12", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 25, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»≥)root.encoder_blocks.0.mha.lin_qry_heads.4"_tf_keras_layer*Ä{"name": "linear_13", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_13", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 26, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»¥)root.encoder_blocks.0.mha.lin_qry_heads.5"_tf_keras_layer*Ä{"name": "linear_14", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_14", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 27, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»µ)root.encoder_blocks.0.mha.lin_qry_heads.6"_tf_keras_layer*Ä{"name": "linear_15", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_15", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 28, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»∂)root.encoder_blocks.0.mha.lin_qry_heads.7"_tf_keras_layer*Ä{"name": "linear_16", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_16", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 29, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»∑)root.encoder_blocks.0.mha.lin_val_heads.0"_tf_keras_layer*Ä{"name": "linear_17", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_17", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 30, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»∏)root.encoder_blocks.0.mha.lin_val_heads.1"_tf_keras_layer*Ä{"name": "linear_18", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_18", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 31, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»π)root.encoder_blocks.0.mha.lin_val_heads.2"_tf_keras_layer*Ä{"name": "linear_19", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_19", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 32, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»∫)root.encoder_blocks.0.mha.lin_val_heads.3"_tf_keras_layer*Ä{"name": "linear_20", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_20", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 33, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»ª)root.encoder_blocks.0.mha.lin_val_heads.4"_tf_keras_layer*Ä{"name": "linear_21", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_21", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 34, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»º)root.encoder_blocks.0.mha.lin_val_heads.5"_tf_keras_layer*Ä{"name": "linear_22", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_22", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 35, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»Ω)root.encoder_blocks.0.mha.lin_val_heads.6"_tf_keras_layer*Ä{"name": "linear_23", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_23", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 36, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
»æ)root.encoder_blocks.0.mha.lin_val_heads.7"_tf_keras_layer*Ä{"name": "linear_24", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_24", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 37, "build_input_shape": {"class_name": "TensorShape", "items": [null, 196, 256]}}2
áø;root.encoder_blocks.0.mha.scaled_dot_prod_attention.softmax"_tf_keras_layer*≠{"name": "softmax", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Softmax", "config": {"name": "softmax", "trainable": true, "dtype": "float32", "axis": -1}, "shared_object_id": 38}2