
˙root"_tf_keras_model*⁄{"name": "co_vi_t_model", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "CoViTModel", "config": {"layer was saved without config": true}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [1, 192, 256, 4]}, "float32", "input_1"]}], {}]}, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [1, 192, 256, 4]}, "float32", "input_1"]}, "keras_version": "2.8.0", "backend": "tensorflow", "model_config": {"class_name": "CoViTModel"}, "training_config": {"loss": "categorical_crossentropy", "metrics": [[{"class_name": "TopKCategoricalAccuracy", "config": {"name": "top1_accuracy", "dtype": "float32", "k": 1}, "shared_object_id": 0}, {"class_name": "TopKCategoricalAccuracy", "config": {"name": "top2_accuracy", "dtype": "float32", "k": 2}, "shared_object_id": 1}, {"class_name": "TopKCategoricalAccuracy", "config": {"name": "top5_accuracy", "dtype": "float32", "k": 5}, "shared_object_id": 2}]], "weighted_metrics": null, "loss_weights": null, "optimizer_config": {"class_name": "Adam", "config": {"name": "Adam", "clipnorm": 1.0, "learning_rate": 0.0010000000474974513, "decay": 0.0, "beta_1": 0.8999999761581421, "beta_2": 0.9990000128746033, "epsilon": 1e-07, "amsgrad": false}}}}2
±root.base_embedding"_tf_keras_layer*Ä{"name": "linear_10", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_10", "trainable": false, "dtype": "float32", "units": 1}, "shared_object_id": 3, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256, 4]}}2
â	root.norm"_tf_keras_layer*‚{"name": "layer_normalization_11", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_11", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 4}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 5}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 6, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∏root.out"_tf_keras_layer*í{"name": "predictor_block_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "PredictorBlock", "config": {"name": "predictor_block_1", "trainable": true, "dtype": "float32", "units": 10}, "shared_object_id": 7, "build_input_shape": {"class_name": "TensorShape", "items": [null, 256]}}2
Ωroot.encoder_blocks.0"_tf_keras_layer*ä{"name": "encoder_block", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderBlock", "config": {"name": "encoder_block", "trainable": false, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 1, "dropout_rate": 0.1, "d_ff": 64}, "shared_object_id": 8}2
øroot.encoder_blocks.1"_tf_keras_layer*å{"name": "encoder_block_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderBlock", "config": {"name": "encoder_block_1", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 1, "dropout_rate": 0.1, "d_ff": 64}, "shared_object_id": 9}2
¿root.encoder_blocks.2"_tf_keras_layer*ç{"name": "encoder_block_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderBlock", "config": {"name": "encoder_block_2", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 1, "dropout_rate": 0.1, "d_ff": 64}, "shared_object_id": 10}2
÷jroot.encoder_blocks.0.mha"_tf_keras_layer*ü{"name": "my_multi_head_attention_2", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "MyMultiHeadAttention", "config": {"name": "my_multi_head_attention_2", "trainable": false, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 1, "dropout_rate": 0.1}, "shared_object_id": 11}2
Ékroot.encoder_blocks.0.ff"_tf_keras_layer*Õ{"name": "feed_forward_2", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "FeedForward", "config": {"name": "feed_forward_2", "trainable": false, "dtype": "float32", "units": 64, "activation": "relu", "outer_units": 256, "dropout_rate": 0.1}, "shared_object_id": 12, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
õlroot.encoder_blocks.0.norm1"_tf_keras_layer*‚{"name": "layer_normalization_4", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_4", "trainable": false, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 13}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 14}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 15, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
õmroot.encoder_blocks.0.norm2"_tf_keras_layer*‚{"name": "layer_normalization_5", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_5", "trainable": false, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 16}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 17}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 18, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
‘troot.encoder_blocks.1.mha"_tf_keras_layer*ù{"name": "my_multi_head_attention_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "MyMultiHeadAttention", "config": {"name": "my_multi_head_attention_3", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 1, "dropout_rate": 0.1}, "shared_object_id": 19}2
Åuroot.encoder_blocks.1.ff"_tf_keras_layer*À{"name": "feed_forward_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "FeedForward", "config": {"name": "feed_forward_3", "trainable": true, "dtype": "float32", "units": 64, "activation": "relu", "outer_units": 256, "dropout_rate": 0.1}, "shared_object_id": 20, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
ôvroot.encoder_blocks.1.norm1"_tf_keras_layer*‡{"name": "layer_normalization_6", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_6", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 21}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 22}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 23, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
ôwroot.encoder_blocks.1.norm2"_tf_keras_layer*‡{"name": "layer_normalization_7", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_7", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 24}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 25}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 26, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
‘~root.encoder_blocks.2.mha"_tf_keras_layer*ù{"name": "my_multi_head_attention_4", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "MyMultiHeadAttention", "config": {"name": "my_multi_head_attention_4", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 1, "dropout_rate": 0.1}, "shared_object_id": 27}2
Ñroot.encoder_blocks.2.ff"_tf_keras_layer*Œ{"name": "feed_forward_4", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "FeedForward", "config": {"name": "feed_forward_4", "trainable": true, "dtype": "float32", "units": 64, "activation": "relu", "outer_units": 256, "dropout_rate": 0.1}, "shared_object_id": 28, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ùÄroot.encoder_blocks.2.norm1"_tf_keras_layer*„{"name": "layer_normalization_9", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_9", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 29}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 30}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 31, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
üÅroot.encoder_blocks.2.norm2"_tf_keras_layer*Â{"name": "layer_normalization_10", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_10", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 32}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 33}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 34, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∫íroot.keras_api.metrics.0"_tf_keras_metric*Ç{"class_name": "Mean", "name": "loss", "dtype": "float32", "config": {"name": "loss", "dtype": "float32"}, "shared_object_id": 35}2
Êìroot.keras_api.metrics.1"_tf_keras_metric*Æ{"class_name": "TopKCategoricalAccuracy", "name": "top1_accuracy", "dtype": "float32", "config": {"name": "top1_accuracy", "dtype": "float32", "k": 1}, "shared_object_id": 0}2
Êîroot.keras_api.metrics.2"_tf_keras_metric*Æ{"class_name": "TopKCategoricalAccuracy", "name": "top2_accuracy", "dtype": "float32", "config": {"name": "top2_accuracy", "dtype": "float32", "k": 2}, "shared_object_id": 1}2
Êïroot.keras_api.metrics.3"_tf_keras_metric*Æ{"class_name": "TopKCategoricalAccuracy", "name": "top5_accuracy", "dtype": "float32", "config": {"name": "top5_accuracy", "dtype": "float32", "k": 5}, "shared_object_id": 2}2
µô3root.encoder_blocks.0.mha.scaled_dot_prod_attention"_tf_keras_layer*„{"name": "scaled_dot_product_attention_2", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ScaledDotProductAttention", "config": {"name": "scaled_dot_product_attention_2", "trainable": false, "dtype": "float32"}, "shared_object_id": 36}2
øö!root.encoder_blocks.0.mha.lin_out"_tf_keras_layer*ˇ{"name": "linear_14", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_14", "trainable": false, "dtype": "float32", "units": 256}, "shared_object_id": 37, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 64]}}2
‚õ!root.encoder_blocks.0.mha.dropout"_tf_keras_layer*¢{"name": "dropout_4", "trainable": false, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_4", "trainable": false, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 38, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
¬¢$root.encoder_blocks.0.ff.outer_layer"_tf_keras_layer*ˇ{"name": "linear_15", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_15", "trainable": false, "dtype": "float32", "units": 256}, "shared_object_id": 39, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 64]}}2
·£ root.encoder_blocks.0.ff.dropout"_tf_keras_layer*¢{"name": "dropout_5", "trainable": false, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_5", "trainable": false, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 40, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
≥¿3root.encoder_blocks.1.mha.scaled_dot_prod_attention"_tf_keras_layer*·{"name": "scaled_dot_product_attention_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ScaledDotProductAttention", "config": {"name": "scaled_dot_product_attention_3", "trainable": true, "dtype": "float32"}, "shared_object_id": 41}2
Ω¡!root.encoder_blocks.1.mha.lin_out"_tf_keras_layer*˝{"name": "linear_19", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_19", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 42, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 64]}}2
‡¬!root.encoder_blocks.1.mha.dropout"_tf_keras_layer*†{"name": "dropout_6", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_6", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 43, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
¿…$root.encoder_blocks.1.ff.outer_layer"_tf_keras_layer*˝{"name": "linear_20", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_20", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 44, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 64]}}2
ﬂ  root.encoder_blocks.1.ff.dropout"_tf_keras_layer*†{"name": "dropout_7", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_7", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 45, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
≥Á3root.encoder_blocks.2.mha.scaled_dot_prod_attention"_tf_keras_layer*·{"name": "scaled_dot_product_attention_4", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ScaledDotProductAttention", "config": {"name": "scaled_dot_product_attention_4", "trainable": true, "dtype": "float32"}, "shared_object_id": 46}2
¿Ë!root.encoder_blocks.2.mha.lin_out"_tf_keras_layer*Ä{"name": "linear_24", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_24", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 47, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 64]}}2
„È!root.encoder_blocks.2.mha.dropout"_tf_keras_layer*£{"name": "dropout_8", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_8", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 48, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
√$root.encoder_blocks.2.ff.outer_layer"_tf_keras_layer*Ä{"name": "linear_25", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_25", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 49, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 64]}}2
‚Ò root.encoder_blocks.2.ff.dropout"_tf_keras_layer*£{"name": "dropout_9", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_9", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 50, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
«û)root.encoder_blocks.0.mha.lin_key_heads.0"_tf_keras_layer*ˇ{"name": "linear_11", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_11", "trainable": false, "dtype": "float32", "units": 64}, "shared_object_id": 51, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
«ü)root.encoder_blocks.0.mha.lin_qry_heads.0"_tf_keras_layer*ˇ{"name": "linear_12", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_12", "trainable": false, "dtype": "float32", "units": 64}, "shared_object_id": 52, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
«†)root.encoder_blocks.0.mha.lin_val_heads.0"_tf_keras_layer*ˇ{"name": "linear_13", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_13", "trainable": false, "dtype": "float32", "units": 64}, "shared_object_id": 53, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
ç°;root.encoder_blocks.0.mha.scaled_dot_prod_attention.softmax"_tf_keras_layer*≥{"name": "softmax_2", "trainable": false, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Softmax", "config": {"name": "softmax_2", "trainable": false, "dtype": "float32", "axis": -1}, "shared_object_id": 54}2
≈÷)root.encoder_blocks.1.mha.lin_key_heads.0"_tf_keras_layer*˝{"name": "linear_16", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_16", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 55, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
≈◊)root.encoder_blocks.1.mha.lin_qry_heads.0"_tf_keras_layer*˝{"name": "linear_17", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_17", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 56, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
≈ÿ)root.encoder_blocks.1.mha.lin_val_heads.0"_tf_keras_layer*˝{"name": "linear_18", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_18", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 57, "build_input_shape": {"class_name": "TensorShape", "items": [1, 192, 256]}}2
ãŸ;root.encoder_blocks.1.mha.scaled_dot_prod_attention.softmax"_tf_keras_layer*±{"name": "softmax_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Softmax", "config": {"name": "softmax_3", "trainable": true, "dtype": "float32", "axis": -1}, "shared_object_id": 58}2
»é)root.encoder_blocks.2.mha.lin_key_heads.0"_tf_keras_layer*Ä{"name": "linear_21", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_21", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 59, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»è)root.encoder_blocks.2.mha.lin_qry_heads.0"_tf_keras_layer*Ä{"name": "linear_22", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_22", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 60, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»ê)root.encoder_blocks.2.mha.lin_val_heads.0"_tf_keras_layer*Ä{"name": "linear_23", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_23", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 61, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ãë;root.encoder_blocks.2.mha.scaled_dot_prod_attention.softmax"_tf_keras_layer*±{"name": "softmax_4", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Softmax", "config": {"name": "softmax_4", "trainable": true, "dtype": "float32", "axis": -1}, "shared_object_id": 62}2