
Äroot"_tf_keras_model*‡{"name": "co_vi_t_model", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "CoViTModel", "config": {"layer was saved without config": true}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 192, 256, 4]}, "float32", "input_1"]}], {}]}, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 192, 256, 4]}, "float32", "input_1"]}, "keras_version": "2.8.0", "backend": "tensorflow", "model_config": {"class_name": "CoViTModel"}, "training_config": {"loss": "categorical_crossentropy", "metrics": [[{"class_name": "TopKCategoricalAccuracy", "config": {"name": "top1_accuracy", "dtype": "float32", "k": 1}, "shared_object_id": 0}, {"class_name": "TopKCategoricalAccuracy", "config": {"name": "top2_accuracy", "dtype": "float32", "k": 2}, "shared_object_id": 1}, {"class_name": "TopKCategoricalAccuracy", "config": {"name": "top5_accuracy", "dtype": "float32", "k": 5}, "shared_object_id": 2}]], "weighted_metrics": null, "loss_weights": null, "optimizer_config": {"class_name": "Adam", "config": {"name": "Adam", "clipnorm": 1.0, "learning_rate": 0.0010000000474974513, "decay": 0.0, "beta_1": 0.8999999761581421, "beta_2": 0.9990000128746033, "epsilon": 1e-07, "amsgrad": false}}}}2
¨root.base_embedding"_tf_keras_layer*˚{"name": "linear", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear", "trainable": true, "dtype": "float32", "units": 1}, "shared_object_id": 3, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256, 4]}}2
á	root.norm"_tf_keras_layer*‡{"name": "layer_normalization_8", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_8", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 4}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 5}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 6, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
¥root.out"_tf_keras_layer*é{"name": "predictor_block", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "PredictorBlock", "config": {"name": "predictor_block", "trainable": true, "dtype": "float32", "units": 10}, "shared_object_id": 7, "build_input_shape": {"class_name": "TensorShape", "items": [null, 256]}}2
æroot.encoder_blocks.0"_tf_keras_layer*ã{"name": "encoder_block", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderBlock", "config": {"name": "encoder_block", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 12, "dropout_rate": 0.1, "d_ff": 1024}, "shared_object_id": 8}2
¬root.encoder_blocks.1"_tf_keras_layer*è{"name": "encoder_block_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderBlock", "config": {"name": "encoder_block_1", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 12, "dropout_rate": 0.1, "d_ff": 1024}, "shared_object_id": 9}2
√root.encoder_blocks.2"_tf_keras_layer*ê{"name": "encoder_block_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderBlock", "config": {"name": "encoder_block_2", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 12, "dropout_rate": 0.1, "d_ff": 1024}, "shared_object_id": 10}2
√root.encoder_blocks.3"_tf_keras_layer*ê{"name": "encoder_block_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderBlock", "config": {"name": "encoder_block_3", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 12, "dropout_rate": 0.1, "d_ff": 1024}, "shared_object_id": 11}2
“Éroot.encoder_blocks.0.mha"_tf_keras_layer*ö{"name": "my_multi_head_attention", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "MyMultiHeadAttention", "config": {"name": "my_multi_head_attention", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 12, "dropout_rate": 0.1}, "shared_object_id": 12}2
ÉÑroot.encoder_blocks.0.ff"_tf_keras_layer*Ã{"name": "feed_forward", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "FeedForward", "config": {"name": "feed_forward", "trainable": true, "dtype": "float32", "units": 1024, "activation": "relu", "outer_units": 256, "dropout_rate": 0.1}, "shared_object_id": 13, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ôÖroot.encoder_blocks.0.norm1"_tf_keras_layer*ﬂ{"name": "layer_normalization", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 14}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 15}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 16, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ùÜroot.encoder_blocks.0.norm2"_tf_keras_layer*„{"name": "layer_normalization_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 17}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 18}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 19, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
÷çroot.encoder_blocks.1.mha"_tf_keras_layer*û{"name": "my_multi_head_attention_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "MyMultiHeadAttention", "config": {"name": "my_multi_head_attention_1", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 12, "dropout_rate": 0.1}, "shared_object_id": 20}2
áéroot.encoder_blocks.1.ff"_tf_keras_layer*–{"name": "feed_forward_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "FeedForward", "config": {"name": "feed_forward_1", "trainable": true, "dtype": "float32", "units": 1024, "activation": "relu", "outer_units": 256, "dropout_rate": 0.1}, "shared_object_id": 21, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ùèroot.encoder_blocks.1.norm1"_tf_keras_layer*„{"name": "layer_normalization_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 22}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 23}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 24, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ùêroot.encoder_blocks.1.norm2"_tf_keras_layer*„{"name": "layer_normalization_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_3", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 25}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 26}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 27, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
÷óroot.encoder_blocks.2.mha"_tf_keras_layer*û{"name": "my_multi_head_attention_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "MyMultiHeadAttention", "config": {"name": "my_multi_head_attention_2", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 12, "dropout_rate": 0.1}, "shared_object_id": 28}2
áòroot.encoder_blocks.2.ff"_tf_keras_layer*–{"name": "feed_forward_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "FeedForward", "config": {"name": "feed_forward_2", "trainable": true, "dtype": "float32", "units": 1024, "activation": "relu", "outer_units": 256, "dropout_rate": 0.1}, "shared_object_id": 29, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ùôroot.encoder_blocks.2.norm1"_tf_keras_layer*„{"name": "layer_normalization_4", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_4", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 30}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 31}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 32, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ùöroot.encoder_blocks.2.norm2"_tf_keras_layer*„{"name": "layer_normalization_5", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_5", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 33}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 34}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 35, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
÷°root.encoder_blocks.3.mha"_tf_keras_layer*û{"name": "my_multi_head_attention_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "MyMultiHeadAttention", "config": {"name": "my_multi_head_attention_3", "trainable": true, "dtype": "float32", "d_key": 64, "d_val": 64, "d_model": 256, "heads": 12, "dropout_rate": 0.1}, "shared_object_id": 36}2
á¢root.encoder_blocks.3.ff"_tf_keras_layer*–{"name": "feed_forward_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "FeedForward", "config": {"name": "feed_forward_3", "trainable": true, "dtype": "float32", "units": 1024, "activation": "relu", "outer_units": 256, "dropout_rate": 0.1}, "shared_object_id": 37, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ù£root.encoder_blocks.3.norm1"_tf_keras_layer*„{"name": "layer_normalization_6", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_6", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 38}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 39}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 40, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ù§root.encoder_blocks.3.norm2"_tf_keras_layer*„{"name": "layer_normalization_7", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "layer_normalization_7", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 41}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 42}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 43, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∫µroot.keras_api.metrics.0"_tf_keras_metric*Ç{"class_name": "Mean", "name": "loss", "dtype": "float32", "config": {"name": "loss", "dtype": "float32"}, "shared_object_id": 44}2
Ê∂root.keras_api.metrics.1"_tf_keras_metric*Æ{"class_name": "TopKCategoricalAccuracy", "name": "top1_accuracy", "dtype": "float32", "config": {"name": "top1_accuracy", "dtype": "float32", "k": 1}, "shared_object_id": 0}2
Ê∑root.keras_api.metrics.2"_tf_keras_metric*Æ{"class_name": "TopKCategoricalAccuracy", "name": "top2_accuracy", "dtype": "float32", "config": {"name": "top2_accuracy", "dtype": "float32", "k": 2}, "shared_object_id": 1}2
Ê∏root.keras_api.metrics.3"_tf_keras_metric*Æ{"class_name": "TopKCategoricalAccuracy", "name": "top5_accuracy", "dtype": "float32", "config": {"name": "top5_accuracy", "dtype": "float32", "k": 5}, "shared_object_id": 2}2
Øº3root.encoder_blocks.0.mha.scaled_dot_prod_attention"_tf_keras_layer*›{"name": "scaled_dot_product_attention", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ScaledDotProductAttention", "config": {"name": "scaled_dot_product_attention", "trainable": true, "dtype": "float32"}, "shared_object_id": 45}2
¡Ω!root.encoder_blocks.0.mha.lin_out"_tf_keras_layer*Å{"name": "linear_37", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_37", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 46, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 768]}}2
ﬂæ!root.encoder_blocks.0.mha.dropout"_tf_keras_layer*ü{"name": "dropout", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 47, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
≈≈$root.encoder_blocks.0.ff.outer_layer"_tf_keras_layer*Ç{"name": "linear_38", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_38", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 48, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 1024]}}2
‚∆ root.encoder_blocks.0.ff.dropout"_tf_keras_layer*£{"name": "dropout_1", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_1", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 49, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
≥„3root.encoder_blocks.1.mha.scaled_dot_prod_attention"_tf_keras_layer*·{"name": "scaled_dot_product_attention_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ScaledDotProductAttention", "config": {"name": "scaled_dot_product_attention_1", "trainable": true, "dtype": "float32"}, "shared_object_id": 50}2
¡‰!root.encoder_blocks.1.mha.lin_out"_tf_keras_layer*Å{"name": "linear_75", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_75", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 51, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 768]}}2
„Â!root.encoder_blocks.1.mha.dropout"_tf_keras_layer*£{"name": "dropout_2", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_2", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 52, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
≈Ï$root.encoder_blocks.1.ff.outer_layer"_tf_keras_layer*Ç{"name": "linear_76", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_76", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 53, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 1024]}}2
‚Ì root.encoder_blocks.1.ff.dropout"_tf_keras_layer*£{"name": "dropout_3", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_3", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 54, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
≥ä3root.encoder_blocks.2.mha.scaled_dot_prod_attention"_tf_keras_layer*·{"name": "scaled_dot_product_attention_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ScaledDotProductAttention", "config": {"name": "scaled_dot_product_attention_2", "trainable": true, "dtype": "float32"}, "shared_object_id": 55}2
√ã!root.encoder_blocks.2.mha.lin_out"_tf_keras_layer*É{"name": "linear_113", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_113", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 56, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 768]}}2
„å!root.encoder_blocks.2.mha.dropout"_tf_keras_layer*£{"name": "dropout_4", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_4", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 57, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
«ì$root.encoder_blocks.2.ff.outer_layer"_tf_keras_layer*Ñ{"name": "linear_114", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_114", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 58, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 1024]}}2
‚î root.encoder_blocks.2.ff.dropout"_tf_keras_layer*£{"name": "dropout_5", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_5", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 59, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
≥±3root.encoder_blocks.3.mha.scaled_dot_prod_attention"_tf_keras_layer*·{"name": "scaled_dot_product_attention_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ScaledDotProductAttention", "config": {"name": "scaled_dot_product_attention_3", "trainable": true, "dtype": "float32"}, "shared_object_id": 60}2
√≤!root.encoder_blocks.3.mha.lin_out"_tf_keras_layer*É{"name": "linear_151", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_151", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 61, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 768]}}2
„≥!root.encoder_blocks.3.mha.dropout"_tf_keras_layer*£{"name": "dropout_6", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_6", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 62, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
«∫$root.encoder_blocks.3.ff.outer_layer"_tf_keras_layer*Ñ{"name": "linear_152", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_152", "trainable": true, "dtype": "float32", "units": 256}, "shared_object_id": 63, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 1024]}}2
‚ª root.encoder_blocks.3.ff.dropout"_tf_keras_layer*£{"name": "dropout_7", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_7", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 64, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆Ë)root.encoder_blocks.0.mha.lin_key_heads.0"_tf_keras_layer*˛{"name": "linear_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_1", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 65, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆È)root.encoder_blocks.0.mha.lin_key_heads.1"_tf_keras_layer*˛{"name": "linear_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_2", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 66, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆Í)root.encoder_blocks.0.mha.lin_key_heads.2"_tf_keras_layer*˛{"name": "linear_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_3", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 67, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆Î)root.encoder_blocks.0.mha.lin_key_heads.3"_tf_keras_layer*˛{"name": "linear_4", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_4", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 68, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆Ï)root.encoder_blocks.0.mha.lin_key_heads.4"_tf_keras_layer*˛{"name": "linear_5", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_5", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 69, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆Ì)root.encoder_blocks.0.mha.lin_key_heads.5"_tf_keras_layer*˛{"name": "linear_6", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_6", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 70, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆Ó)root.encoder_blocks.0.mha.lin_key_heads.6"_tf_keras_layer*˛{"name": "linear_7", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_7", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 71, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆Ô)root.encoder_blocks.0.mha.lin_key_heads.7"_tf_keras_layer*˛{"name": "linear_8", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_8", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 72, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
∆)root.encoder_blocks.0.mha.lin_key_heads.8"_tf_keras_layer*˛{"name": "linear_9", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_9", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 73, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ò)root.encoder_blocks.0.mha.lin_key_heads.9"_tf_keras_layer*Ä{"name": "linear_10", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_10", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 74, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…Ú*root.encoder_blocks.0.mha.lin_key_heads.10"_tf_keras_layer*Ä{"name": "linear_11", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_11", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 75, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…Û*root.encoder_blocks.0.mha.lin_key_heads.11"_tf_keras_layer*Ä{"name": "linear_12", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_12", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 76, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ù)root.encoder_blocks.0.mha.lin_qry_heads.0"_tf_keras_layer*Ä{"name": "linear_13", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_13", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 77, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»ı)root.encoder_blocks.0.mha.lin_qry_heads.1"_tf_keras_layer*Ä{"name": "linear_14", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_14", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 78, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»ˆ)root.encoder_blocks.0.mha.lin_qry_heads.2"_tf_keras_layer*Ä{"name": "linear_15", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_15", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 79, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»˜)root.encoder_blocks.0.mha.lin_qry_heads.3"_tf_keras_layer*Ä{"name": "linear_16", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_16", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 80, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»¯)root.encoder_blocks.0.mha.lin_qry_heads.4"_tf_keras_layer*Ä{"name": "linear_17", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_17", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 81, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»˘)root.encoder_blocks.0.mha.lin_qry_heads.5"_tf_keras_layer*Ä{"name": "linear_18", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_18", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 82, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»˙)root.encoder_blocks.0.mha.lin_qry_heads.6"_tf_keras_layer*Ä{"name": "linear_19", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_19", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 83, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»˚)root.encoder_blocks.0.mha.lin_qry_heads.7"_tf_keras_layer*Ä{"name": "linear_20", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_20", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 84, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»¸)root.encoder_blocks.0.mha.lin_qry_heads.8"_tf_keras_layer*Ä{"name": "linear_21", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_21", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 85, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»˝)root.encoder_blocks.0.mha.lin_qry_heads.9"_tf_keras_layer*Ä{"name": "linear_22", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_22", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 86, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…˛*root.encoder_blocks.0.mha.lin_qry_heads.10"_tf_keras_layer*Ä{"name": "linear_23", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_23", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 87, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…ˇ*root.encoder_blocks.0.mha.lin_qry_heads.11"_tf_keras_layer*Ä{"name": "linear_24", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_24", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 88, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ä)root.encoder_blocks.0.mha.lin_val_heads.0"_tf_keras_layer*Ä{"name": "linear_25", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_25", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 89, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Å)root.encoder_blocks.0.mha.lin_val_heads.1"_tf_keras_layer*Ä{"name": "linear_26", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_26", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 90, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ç)root.encoder_blocks.0.mha.lin_val_heads.2"_tf_keras_layer*Ä{"name": "linear_27", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_27", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 91, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»É)root.encoder_blocks.0.mha.lin_val_heads.3"_tf_keras_layer*Ä{"name": "linear_28", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_28", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 92, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ñ)root.encoder_blocks.0.mha.lin_val_heads.4"_tf_keras_layer*Ä{"name": "linear_29", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_29", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 93, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ö)root.encoder_blocks.0.mha.lin_val_heads.5"_tf_keras_layer*Ä{"name": "linear_30", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_30", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 94, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»Ü)root.encoder_blocks.0.mha.lin_val_heads.6"_tf_keras_layer*Ä{"name": "linear_31", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_31", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 95, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»á)root.encoder_blocks.0.mha.lin_val_heads.7"_tf_keras_layer*Ä{"name": "linear_32", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_32", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 96, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»à)root.encoder_blocks.0.mha.lin_val_heads.8"_tf_keras_layer*Ä{"name": "linear_33", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_33", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 97, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
»â)root.encoder_blocks.0.mha.lin_val_heads.9"_tf_keras_layer*Ä{"name": "linear_34", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_34", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 98, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…ä*root.encoder_blocks.0.mha.lin_val_heads.10"_tf_keras_layer*Ä{"name": "linear_35", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_35", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 99, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
 ã*root.encoder_blocks.0.mha.lin_val_heads.11"_tf_keras_layer*Å{"name": "linear_36", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_36", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 100, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
àå;root.encoder_blocks.0.mha.scaled_dot_prod_attention.softmax"_tf_keras_layer*Æ{"name": "softmax", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Softmax", "config": {"name": "softmax", "trainable": true, "dtype": "float32", "axis": -1}, "shared_object_id": 101}2
…¡)root.encoder_blocks.1.mha.lin_key_heads.0"_tf_keras_layer*Å{"name": "linear_39", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_39", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 102, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…¬)root.encoder_blocks.1.mha.lin_key_heads.1"_tf_keras_layer*Å{"name": "linear_40", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_40", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 103, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…√)root.encoder_blocks.1.mha.lin_key_heads.2"_tf_keras_layer*Å{"name": "linear_41", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_41", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 104, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…ƒ)root.encoder_blocks.1.mha.lin_key_heads.3"_tf_keras_layer*Å{"name": "linear_42", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_42", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 105, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…≈)root.encoder_blocks.1.mha.lin_key_heads.4"_tf_keras_layer*Å{"name": "linear_43", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_43", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 106, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…∆)root.encoder_blocks.1.mha.lin_key_heads.5"_tf_keras_layer*Å{"name": "linear_44", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_44", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 107, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…«)root.encoder_blocks.1.mha.lin_key_heads.6"_tf_keras_layer*Å{"name": "linear_45", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_45", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 108, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…»)root.encoder_blocks.1.mha.lin_key_heads.7"_tf_keras_layer*Å{"name": "linear_46", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_46", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 109, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
……)root.encoder_blocks.1.mha.lin_key_heads.8"_tf_keras_layer*Å{"name": "linear_47", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_47", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 110, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
… )root.encoder_blocks.1.mha.lin_key_heads.9"_tf_keras_layer*Å{"name": "linear_48", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_48", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 111, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
 À*root.encoder_blocks.1.mha.lin_key_heads.10"_tf_keras_layer*Å{"name": "linear_49", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_49", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 112, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
 Ã*root.encoder_blocks.1.mha.lin_key_heads.11"_tf_keras_layer*Å{"name": "linear_50", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_50", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 113, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…Õ)root.encoder_blocks.1.mha.lin_qry_heads.0"_tf_keras_layer*Å{"name": "linear_51", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_51", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 114, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…Œ)root.encoder_blocks.1.mha.lin_qry_heads.1"_tf_keras_layer*Å{"name": "linear_52", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_52", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 115, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…œ)root.encoder_blocks.1.mha.lin_qry_heads.2"_tf_keras_layer*Å{"name": "linear_53", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_53", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 116, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…–)root.encoder_blocks.1.mha.lin_qry_heads.3"_tf_keras_layer*Å{"name": "linear_54", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_54", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 117, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…—)root.encoder_blocks.1.mha.lin_qry_heads.4"_tf_keras_layer*Å{"name": "linear_55", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_55", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 118, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…“)root.encoder_blocks.1.mha.lin_qry_heads.5"_tf_keras_layer*Å{"name": "linear_56", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_56", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 119, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…”)root.encoder_blocks.1.mha.lin_qry_heads.6"_tf_keras_layer*Å{"name": "linear_57", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_57", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 120, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…‘)root.encoder_blocks.1.mha.lin_qry_heads.7"_tf_keras_layer*Å{"name": "linear_58", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_58", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 121, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…’)root.encoder_blocks.1.mha.lin_qry_heads.8"_tf_keras_layer*Å{"name": "linear_59", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_59", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 122, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…÷)root.encoder_blocks.1.mha.lin_qry_heads.9"_tf_keras_layer*Å{"name": "linear_60", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_60", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 123, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
 ◊*root.encoder_blocks.1.mha.lin_qry_heads.10"_tf_keras_layer*Å{"name": "linear_61", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_61", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 124, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
 ÿ*root.encoder_blocks.1.mha.lin_qry_heads.11"_tf_keras_layer*Å{"name": "linear_62", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_62", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 125, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…Ÿ)root.encoder_blocks.1.mha.lin_val_heads.0"_tf_keras_layer*Å{"name": "linear_63", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_63", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 126, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…⁄)root.encoder_blocks.1.mha.lin_val_heads.1"_tf_keras_layer*Å{"name": "linear_64", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_64", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 127, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…€)root.encoder_blocks.1.mha.lin_val_heads.2"_tf_keras_layer*Å{"name": "linear_65", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_65", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 128, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…‹)root.encoder_blocks.1.mha.lin_val_heads.3"_tf_keras_layer*Å{"name": "linear_66", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_66", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 129, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…›)root.encoder_blocks.1.mha.lin_val_heads.4"_tf_keras_layer*Å{"name": "linear_67", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_67", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 130, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…ﬁ)root.encoder_blocks.1.mha.lin_val_heads.5"_tf_keras_layer*Å{"name": "linear_68", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_68", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 131, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…ﬂ)root.encoder_blocks.1.mha.lin_val_heads.6"_tf_keras_layer*Å{"name": "linear_69", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_69", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 132, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…‡)root.encoder_blocks.1.mha.lin_val_heads.7"_tf_keras_layer*Å{"name": "linear_70", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_70", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 133, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…·)root.encoder_blocks.1.mha.lin_val_heads.8"_tf_keras_layer*Å{"name": "linear_71", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_71", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 134, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…‚)root.encoder_blocks.1.mha.lin_val_heads.9"_tf_keras_layer*Å{"name": "linear_72", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_72", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 135, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
 „*root.encoder_blocks.1.mha.lin_val_heads.10"_tf_keras_layer*Å{"name": "linear_73", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_73", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 136, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
 ‰*root.encoder_blocks.1.mha.lin_val_heads.11"_tf_keras_layer*Å{"name": "linear_74", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_74", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 137, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
åÂ;root.encoder_blocks.1.mha.scaled_dot_prod_attention.softmax"_tf_keras_layer*≤{"name": "softmax_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Softmax", "config": {"name": "softmax_1", "trainable": true, "dtype": "float32", "axis": -1}, "shared_object_id": 138}2
…ö)root.encoder_blocks.2.mha.lin_key_heads.0"_tf_keras_layer*Å{"name": "linear_77", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_77", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 139, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…õ)root.encoder_blocks.2.mha.lin_key_heads.1"_tf_keras_layer*Å{"name": "linear_78", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_78", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 140, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…ú)root.encoder_blocks.2.mha.lin_key_heads.2"_tf_keras_layer*Å{"name": "linear_79", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_79", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 141, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…ù)root.encoder_blocks.2.mha.lin_key_heads.3"_tf_keras_layer*Å{"name": "linear_80", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_80", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 142, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…û)root.encoder_blocks.2.mha.lin_key_heads.4"_tf_keras_layer*Å{"name": "linear_81", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_81", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 143, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…ü)root.encoder_blocks.2.mha.lin_key_heads.5"_tf_keras_layer*Å{"name": "linear_82", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_82", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 144, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…†)root.encoder_blocks.2.mha.lin_key_heads.6"_tf_keras_layer*Å{"name": "linear_83", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_83", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 145, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…°)root.encoder_blocks.2.mha.lin_key_heads.7"_tf_keras_layer*Å{"name": "linear_84", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_84", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 146, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…¢)root.encoder_blocks.2.mha.lin_key_heads.8"_tf_keras_layer*Å{"name": "linear_85", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_85", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 147, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…£)root.encoder_blocks.2.mha.lin_key_heads.9"_tf_keras_layer*Å{"name": "linear_86", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_86", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 148, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
 §*root.encoder_blocks.2.mha.lin_key_heads.10"_tf_keras_layer*Å{"name": "linear_87", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_87", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 149, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
 •*root.encoder_blocks.2.mha.lin_key_heads.11"_tf_keras_layer*Å{"name": "linear_88", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_88", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 150, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…¶)root.encoder_blocks.2.mha.lin_qry_heads.0"_tf_keras_layer*Å{"name": "linear_89", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_89", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 151, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…ß)root.encoder_blocks.2.mha.lin_qry_heads.1"_tf_keras_layer*Å{"name": "linear_90", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_90", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 152, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…®)root.encoder_blocks.2.mha.lin_qry_heads.2"_tf_keras_layer*Å{"name": "linear_91", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_91", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 153, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…©)root.encoder_blocks.2.mha.lin_qry_heads.3"_tf_keras_layer*Å{"name": "linear_92", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_92", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 154, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…™)root.encoder_blocks.2.mha.lin_qry_heads.4"_tf_keras_layer*Å{"name": "linear_93", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_93", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 155, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…´)root.encoder_blocks.2.mha.lin_qry_heads.5"_tf_keras_layer*Å{"name": "linear_94", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_94", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 156, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…¨)root.encoder_blocks.2.mha.lin_qry_heads.6"_tf_keras_layer*Å{"name": "linear_95", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_95", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 157, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…≠)root.encoder_blocks.2.mha.lin_qry_heads.7"_tf_keras_layer*Å{"name": "linear_96", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_96", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 158, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…Æ)root.encoder_blocks.2.mha.lin_qry_heads.8"_tf_keras_layer*Å{"name": "linear_97", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_97", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 159, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
…Ø)root.encoder_blocks.2.mha.lin_qry_heads.9"_tf_keras_layer*Å{"name": "linear_98", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_98", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 160, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
 ∞*root.encoder_blocks.2.mha.lin_qry_heads.10"_tf_keras_layer*Å{"name": "linear_99", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_99", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 161, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Ã±*root.encoder_blocks.2.mha.lin_qry_heads.11"_tf_keras_layer*É{"name": "linear_100", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_100", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 162, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À≤)root.encoder_blocks.2.mha.lin_val_heads.0"_tf_keras_layer*É{"name": "linear_101", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_101", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 163, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À≥)root.encoder_blocks.2.mha.lin_val_heads.1"_tf_keras_layer*É{"name": "linear_102", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_102", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 164, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À¥)root.encoder_blocks.2.mha.lin_val_heads.2"_tf_keras_layer*É{"name": "linear_103", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_103", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 165, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àµ)root.encoder_blocks.2.mha.lin_val_heads.3"_tf_keras_layer*É{"name": "linear_104", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_104", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 166, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À∂)root.encoder_blocks.2.mha.lin_val_heads.4"_tf_keras_layer*É{"name": "linear_105", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_105", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 167, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À∑)root.encoder_blocks.2.mha.lin_val_heads.5"_tf_keras_layer*É{"name": "linear_106", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_106", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 168, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À∏)root.encoder_blocks.2.mha.lin_val_heads.6"_tf_keras_layer*É{"name": "linear_107", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_107", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 169, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àπ)root.encoder_blocks.2.mha.lin_val_heads.7"_tf_keras_layer*É{"name": "linear_108", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_108", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 170, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À∫)root.encoder_blocks.2.mha.lin_val_heads.8"_tf_keras_layer*É{"name": "linear_109", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_109", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 171, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àª)root.encoder_blocks.2.mha.lin_val_heads.9"_tf_keras_layer*É{"name": "linear_110", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_110", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 172, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Ãº*root.encoder_blocks.2.mha.lin_val_heads.10"_tf_keras_layer*É{"name": "linear_111", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_111", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 173, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ÃΩ*root.encoder_blocks.2.mha.lin_val_heads.11"_tf_keras_layer*É{"name": "linear_112", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_112", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 174, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
åæ;root.encoder_blocks.2.mha.scaled_dot_prod_attention.softmax"_tf_keras_layer*≤{"name": "softmax_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Softmax", "config": {"name": "softmax_2", "trainable": true, "dtype": "float32", "axis": -1}, "shared_object_id": 175}2
ÀÛ)root.encoder_blocks.3.mha.lin_key_heads.0"_tf_keras_layer*É{"name": "linear_115", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_115", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 176, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ÀÙ)root.encoder_blocks.3.mha.lin_key_heads.1"_tf_keras_layer*É{"name": "linear_116", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_116", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 177, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àı)root.encoder_blocks.3.mha.lin_key_heads.2"_tf_keras_layer*É{"name": "linear_117", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_117", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 178, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àˆ)root.encoder_blocks.3.mha.lin_key_heads.3"_tf_keras_layer*É{"name": "linear_118", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_118", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 179, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À˜)root.encoder_blocks.3.mha.lin_key_heads.4"_tf_keras_layer*É{"name": "linear_119", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_119", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 180, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À¯)root.encoder_blocks.3.mha.lin_key_heads.5"_tf_keras_layer*É{"name": "linear_120", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_120", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 181, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À˘)root.encoder_blocks.3.mha.lin_key_heads.6"_tf_keras_layer*É{"name": "linear_121", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_121", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 182, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À˙)root.encoder_blocks.3.mha.lin_key_heads.7"_tf_keras_layer*É{"name": "linear_122", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_122", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 183, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À˚)root.encoder_blocks.3.mha.lin_key_heads.8"_tf_keras_layer*É{"name": "linear_123", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_123", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 184, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
À¸)root.encoder_blocks.3.mha.lin_key_heads.9"_tf_keras_layer*É{"name": "linear_124", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_124", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 185, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Ã˝*root.encoder_blocks.3.mha.lin_key_heads.10"_tf_keras_layer*É{"name": "linear_125", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_125", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 186, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Ã˛*root.encoder_blocks.3.mha.lin_key_heads.11"_tf_keras_layer*É{"name": "linear_126", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_126", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 187, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àˇ)root.encoder_blocks.3.mha.lin_qry_heads.0"_tf_keras_layer*É{"name": "linear_127", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_127", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 188, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ÀÄ)root.encoder_blocks.3.mha.lin_qry_heads.1"_tf_keras_layer*É{"name": "linear_128", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_128", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 189, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ÀÅ)root.encoder_blocks.3.mha.lin_qry_heads.2"_tf_keras_layer*É{"name": "linear_129", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_129", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 190, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ÀÇ)root.encoder_blocks.3.mha.lin_qry_heads.3"_tf_keras_layer*É{"name": "linear_130", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_130", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 191, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ÀÉ)root.encoder_blocks.3.mha.lin_qry_heads.4"_tf_keras_layer*É{"name": "linear_131", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_131", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 192, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ÀÑ)root.encoder_blocks.3.mha.lin_qry_heads.5"_tf_keras_layer*É{"name": "linear_132", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_132", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 193, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ÀÖ)root.encoder_blocks.3.mha.lin_qry_heads.6"_tf_keras_layer*É{"name": "linear_133", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_133", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 194, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
ÀÜ)root.encoder_blocks.3.mha.lin_qry_heads.7"_tf_keras_layer*É{"name": "linear_134", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_134", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 195, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àá)root.encoder_blocks.3.mha.lin_qry_heads.8"_tf_keras_layer*É{"name": "linear_135", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_135", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 196, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àà)root.encoder_blocks.3.mha.lin_qry_heads.9"_tf_keras_layer*É{"name": "linear_136", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_136", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 197, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Ãâ*root.encoder_blocks.3.mha.lin_qry_heads.10"_tf_keras_layer*É{"name": "linear_137", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_137", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 198, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Ãä*root.encoder_blocks.3.mha.lin_qry_heads.11"_tf_keras_layer*É{"name": "linear_138", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_138", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 199, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àã)root.encoder_blocks.3.mha.lin_val_heads.0"_tf_keras_layer*É{"name": "linear_139", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_139", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 200, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àå)root.encoder_blocks.3.mha.lin_val_heads.1"_tf_keras_layer*É{"name": "linear_140", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_140", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 201, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àç)root.encoder_blocks.3.mha.lin_val_heads.2"_tf_keras_layer*É{"name": "linear_141", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_141", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 202, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àé)root.encoder_blocks.3.mha.lin_val_heads.3"_tf_keras_layer*É{"name": "linear_142", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_142", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 203, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àè)root.encoder_blocks.3.mha.lin_val_heads.4"_tf_keras_layer*É{"name": "linear_143", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_143", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 204, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àê)root.encoder_blocks.3.mha.lin_val_heads.5"_tf_keras_layer*É{"name": "linear_144", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_144", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 205, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àë)root.encoder_blocks.3.mha.lin_val_heads.6"_tf_keras_layer*É{"name": "linear_145", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_145", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 206, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àí)root.encoder_blocks.3.mha.lin_val_heads.7"_tf_keras_layer*É{"name": "linear_146", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_146", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 207, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àì)root.encoder_blocks.3.mha.lin_val_heads.8"_tf_keras_layer*É{"name": "linear_147", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_147", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 208, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Àî)root.encoder_blocks.3.mha.lin_val_heads.9"_tf_keras_layer*É{"name": "linear_148", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_148", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 209, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Ãï*root.encoder_blocks.3.mha.lin_val_heads.10"_tf_keras_layer*É{"name": "linear_149", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_149", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 210, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
Ãñ*root.encoder_blocks.3.mha.lin_val_heads.11"_tf_keras_layer*É{"name": "linear_150", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Linear", "config": {"name": "linear_150", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 211, "build_input_shape": {"class_name": "TensorShape", "items": [null, 192, 256]}}2
åó;root.encoder_blocks.3.mha.scaled_dot_prod_attention.softmax"_tf_keras_layer*≤{"name": "softmax_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Softmax", "config": {"name": "softmax_3", "trainable": true, "dtype": "float32", "axis": -1}, "shared_object_id": 212}2