# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Genome.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cGenome.proto\x12\x08\x44\x65\x65pSars\"C\n\x06Genome\x12\x11\n\taccession\x18\x01 \x01(\t\x12\x12\n\ngenome_len\x18\x02 \x01(\x05\x12\x12\n\ngenome_seq\x18\x03 \x01(\tb\x06proto3')



_GENOME = DESCRIPTOR.message_types_by_name['Genome']
Genome = _reflection.GeneratedProtocolMessageType('Genome', (_message.Message,), {
  'DESCRIPTOR' : _GENOME,
  '__module__' : 'Genome_pb2'
  # @@protoc_insertion_point(class_scope:DeepSars.Genome)
  })
_sym_db.RegisterMessage(Genome)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENOME._serialized_start=26
  _GENOME._serialized_end=93
# @@protoc_insertion_point(module_scope)
